
######################### Configuration snakemake #############################

## -----------------------------------> variable path pipeline 

# Path of results

pathresults: "/env/cng/proj/LEE/pipelines/DNAMethBS_pipeline/Results/"

# Switch reference genome Populus Trichocarpa V3/V4 

REF_GENOME: "/env/cng/proj/LEE/pipelines/DNAMethBS_pipeline/Ref_trichocarpa/Ptrichocarpa_444_v3.0.fa"
#REF_GENOME: "/env/cng/proj/LEE/pipelines/DNAMethBS_pipeline/Ref_trichocarpa/Ptrichocarpa_533_v4.0.fa"

# Number of samples for modeling THREADS of each rule in the pipeline

NBSAMPLE: 1


## -----------------------------------> Settings softwars


# All default settings except trimgalore :

# Params_trimgalore
 
ERROR_RATE: 0.1
LENGTH: 36
QUALITY: 20
ADAPTER1: --illumina
ADAPTER2: AAATCAAAAAAAC

## rule duplicate specify ON-Target


# SELECT EITHER BY SPECIFY THE ONTARGET (1) OR NOT (0)
Target: 0

#Path the file bed 
pathbed: "/env/cng/proj/LEE/pipelines/DNAMethBS_pipeline/script/merge_covered.bed"

## -----------------------------------> path pipeline 

#  Path environnement pipeline 

path-work-env: "/env/cng/proj/LEE/pipelines/DNAMethBS_pipeline/"

# Software_path GitHub Repository (https://github.com/zyndagj/BSMAPz)

tools: "/env/cng/proj/LEE/pipelines/DNAMethBS_pipeline/Tools/BSMAPz-master"

# Wildcard 

CONTEXT: ['CG', 'CHH', 'CHG']
READS: ['1', '2']

#--------------------------------------------------------------------------------------------






